version: '3.8'

services:
  ibmmq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: ibmmq-ci
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"
    volumes:
      - qm1data:/mnt/mqm
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      MQ_ENABLE_METRICS: "true"
      MQ_ADMIN_PASSWORD: admin
      MQ_ENABLE_EMBEDDED_WEB_SERVER: "true"
      MQ_LOGGING_CONSOLE_SOURCE: "true"
      MQ_LOGGING_CONSOLE_FORMAT: "json"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "dspmq", "-m", "QM1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    networks:
      - mq-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-ci
    ports:
      - "10201:5432"
    environment:
      POSTGRES_DB: mqdb
      POSTGRES_USER: mquser
      POSTGRES_PASSWORD: mqpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mq-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mquser -d mqdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  qm1data:
  postgres_data:

networks:
  mq-network:
    driver: bridge